/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Add */

#ifndef _Included_Add
#define _Included_Add
#ifdef __cplusplus
extern "C" {
#endif
#undef Add_serialVersionUID
#define Add_serialVersionUID 1i64
#undef Add_serialVersionUID
#define Add_serialVersionUID 1i64
/*
 * Class:     Add
 * Method:    addBook
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_Add_addBook
  (JNIEnv *, jobject, jint, jstring, jstring, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
