/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Borrow */

#ifndef _Included_Borrow
#define _Included_Borrow
#ifdef __cplusplus
extern "C" {
#endif
#undef Borrow_serialVersionUID
#define Borrow_serialVersionUID 1i64
#undef Borrow_serialVersionUID
#define Borrow_serialVersionUID 1i64
/*
 * Class:     Borrow
 * Method:    borrowBook
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Borrow_borrowBook
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
