/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Delete */

#ifndef _Included_Delete
#define _Included_Delete
#ifdef __cplusplus
extern "C" {
#endif
#undef Delete_serialVersionUID
#define Delete_serialVersionUID 1i64
#undef Delete_serialVersionUID
#define Delete_serialVersionUID 1i64
/*
 * Class:     Delete
 * Method:    deleteBook
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Delete_deleteBook
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
