/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Login */

#ifndef _Included_Login
#define _Included_Login
#ifdef __cplusplus
extern "C" {
#endif
#undef Login_serialVersionUID
#define Login_serialVersionUID 1i64
#undef Login_serialVersionUID
#define Login_serialVersionUID 1i64
/*
 * Class:     Login
 * Method:    checkadmin
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_Login_checkadmin
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     Login
 * Method:    checkuser
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_Login_checkuser
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
