/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyBooks */

#ifndef _Included_MyBooks
#define _Included_MyBooks
#ifdef __cplusplus
extern "C" {
#endif
#undef MyBooks_serialVersionUID
#define MyBooks_serialVersionUID 1i64
#undef MyBooks_serialVersionUID
#define MyBooks_serialVersionUID 1i64
/*
 * Class:     MyBooks
 * Method:    BorrowedBooks
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_MyBooks_BorrowedBooks
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
