/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Return */

#ifndef _Included_Return
#define _Included_Return
#ifdef __cplusplus
extern "C" {
#endif
#undef Return_serialVersionUID
#define Return_serialVersionUID 1i64
#undef Return_serialVersionUID
#define Return_serialVersionUID 1i64
/*
 * Class:     Return
 * Method:    returnBook
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Return_returnBook
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
