/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Search */

#ifndef _Included_Search
#define _Included_Search
#ifdef __cplusplus
extern "C" {
#endif
#undef Search_serialVersionUID
#define Search_serialVersionUID 1i64
#undef Search_serialVersionUID
#define Search_serialVersionUID 1i64
/*
 * Class:     Search
 * Method:    searchBook
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Search_searchBook
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
