/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Update */

#ifndef _Included_Update
#define _Included_Update
#ifdef __cplusplus
extern "C" {
#endif
#undef Update_serialVersionUID
#define Update_serialVersionUID 1i64
#undef Update_serialVersionUID
#define Update_serialVersionUID 1i64
/*
 * Class:     Update
 * Method:    updateBook
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_Update_updateBook
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
