/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ViewAll */

#ifndef _Included_ViewAll
#define _Included_ViewAll
#ifdef __cplusplus
extern "C" {
#endif
#undef ViewAll_serialVersionUID
#define ViewAll_serialVersionUID 1i64
#undef ViewAll_serialVersionUID
#define ViewAll_serialVersionUID 1i64
/*
 * Class:     ViewAll
 * Method:    viewBooks
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ViewAll_viewBooks
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
